import type { TestPlanReport } from '../types';

export function formatReportAsMarkdown(report: TestPlanReport): string {
  const { summary, positiveTests, negativeTests, edgeCases, validationChecks, securityChecks, statusCodes, sampleData, reliabilityRecommendations, riskSummary } = report;

  let md = `# AI API Reliability Test Plan Report
*Generated by AI API Reliability Assistant*
*Analyzed at:* ${new Date(summary.analyzedAt).toLocaleString()}
*Engine:* ${summary.engine}
*Reliability Health Score:* ${summary.reliabilityScore}/100

---

## 1. API Summary
- **Endpoint:** \`${summary.method} ${summary.endpoint}\`
- **Purpose:** ${summary.purpose}
- **Authentication Scheme:** ${summary.authentication}
- **Expected Content-Type:** ${summary.contentType}

### Key Architectural Assumptions:
${summary.assumptions.map((a) => `- ${a}`).join('\n')}

---

## 2. Positive Test Cases
| Test ID | Scenario | Priority | Expected Status | Expected Behaviour |
| :--- | :--- | :--- | :--- | :--- |
${positiveTests
  .map(
    (t) =>
      `| **${t.id}** | ${t.scenario} | \`${t.priority}\` | \`${t.expectedStatus}\` | ${t.expectedBehaviour} |`
  )
  .join('\n')}

---

## 3. Negative Test Cases
| Test ID | Scenario | Priority | Expected Status | Input / Condition | Expected Behaviour |
| :--- | :--- | :--- | :--- | :--- | :--- |
${negativeTests
  .map(
    (t) =>
      `| **${t.id}** | ${t.scenario} | \`${t.priority}\` | \`${t.expectedStatus}\` | \`${t.input.replace(/\n/g, ' ')}\` | ${t.expectedBehaviour} |`
  )
  .join('\n')}

---

## 4. Edge & Boundary Cases
| Test ID | Boundary Scenario | Priority | Expected Status | Expected Behaviour |
| :--- | :--- | :--- | :--- | :--- |
${edgeCases
  .map(
    (t) =>
      `| **${t.id}** | ${t.scenario} | \`${t.priority}\` | \`${t.expectedStatus}\` | ${t.expectedBehaviour} |`
  )
  .join('\n')}

---

## 5. Validation Checks
| Check ID | Category | Target Field | Validation Rule | Status | Priority |
| :--- | :--- | :--- | :--- | :--- | :--- |
${validationChecks
  .map(
    (v) =>
      `| **${v.id}** | ${v.category} | \`${v.field}\` | ${v.rule} | \`${v.expectedStatus}\` | \`${v.priority}\` |`
  )
  .join('\n')}

---

## 6. Authentication & Security Checks
| ID | Category | Scenario | Priority | Expected | Risk & Remediation |
| :--- | :--- | :--- | :--- | :--- | :--- |
${securityChecks
  .map(
    (s) =>
      `| **${s.id}** | ${s.category} | ${s.scenario} | \`${s.priority}\` | \`${s.expectedStatus}\` | **Risk:** ${s.riskDescription}<br>**Defense:** ${s.remediation} |`
  )
  .join('\n')}

---

## 7. HTTP Status Code Expectations
| Status Code | Reason | Category | Scenario |
| :---: | :--- | :--- | :--- |
${statusCodes
  .map(
    (sc) =>
      `| **${sc.status}** | ${sc.reason} | ${sc.category} | ${sc.scenario} |`
  )
  .join('\n')}

---

## 8. Sample Test Data & Scripts
${sampleData
  .map(
    (s) => `### ${s.title} (${s.type.toUpperCase()})
*${s.description}*
\`\`\`${s.format === 'curl' ? 'bash' : 'json'}
${s.payload}
\`\`\`
`
  )
  .join('\n')}

---

## 9. Reliability & Resilience Recommendations
${reliabilityRecommendations
  .map(
    (r) => `### [${r.severity}] ${r.area}: ${r.recommendation}
> **Implementation Guidance:** ${r.guidance}
`
  )
  .join('\n')}

---

## 10. Final Risk Summary & Recommendations

### Critical Risks
${riskSummary.critical.length ? riskSummary.critical.map((r) => `- 🔴 ${r}`).join('\n') : '- None identified'}

### High Risks
${riskSummary.high.length ? riskSummary.high.map((r) => `- 🟠 ${r}`).join('\n') : '- None identified'}

### Medium Risks
${riskSummary.medium.length ? riskSummary.medium.map((r) => `- 🟡 ${r}`).join('\n') : '- None identified'}

### Low Risks
${riskSummary.low.length ? riskSummary.low.map((r) => `- 🔵 ${r}`).join('\n') : '- None identified'}

### Recommended Next Actions
${riskSummary.recommendedActions.map((a) => `- ✅ ${a}`).join('\n')}
`;

  return md;
}

export function formatReportAsPlainText(report: TestPlanReport): string {
  const md = formatReportAsMarkdown(report);
  return md
    .replace(/#+\s/g, '')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\|/g, ' ')
    .replace(/-{3,}/g, '========================================');
}

export function downloadReportFile(report: TestPlanReport, format: 'json' | 'txt' | 'md') {
  let content = '';
  let filename = '';
  let mimeType = '';

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const safeHost = report.summary.endpoint.replace(/https?:\/\//, '').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30);

  if (format === 'json') {
    content = JSON.stringify(report, null, 2);
    filename = `api-reliability-report-${safeHost}-${timestamp}.json`;
    mimeType = 'application/json';
  } else if (format === 'txt') {
    content = formatReportAsPlainText(report);
    filename = `api-reliability-report-${safeHost}-${timestamp}.txt`;
    mimeType = 'text/plain';
  } else {
    content = formatReportAsMarkdown(report);
    filename = `api-reliability-report-${safeHost}-${timestamp}.md`;
    mimeType = 'text/markdown';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
